---
version: 1

name: prometheus-mysqld-exporter
description: Prometheus exporter for MySQL server metrics.
homepage: https://github.com/prometheus/mysqld_exporter

maintainer: Guillaume Durand <guillaume.durand@happn.com>

source:
  url: https://github.com/prometheus/mysqld_exporter/releases/download/v{{ .Version }}/mysqld_exporter-{{ .Version }}.linux-{{ .Arch }}.tar.gz
  strip: 1
  arch-mapping:
    amd64: amd64
    arm64: arm64
    armel: armv6
    armhf: armv7
    i386: "386"

control:
  depends:
  - adduser
  - daemon
  - libc6
  description: |
    Prometheus exporter for MySQL server metrics.
  section: net

install:
  recipe:
    /etc/default:
    - pattern: default
      rename: prometheus-mysqld-exporter
      conffile: true
    /etc/init.d:
    - pattern: init
      rename: prometheus-mysqld-exporter
      conffile: true
  upstream:
    /usr/bin:
    - pattern: mysqld_exporter
    /etc/prometheus/mysql:
    - pattern: mysql.yml

dirs:
- /var/lib/prometheus
- /var/log/prometheus

# vim: ts=2 sw=2 et
