---
version: 1

name: golang-go
description: the Go programming language
homepage: https://golang.org/

maintainer: Recipes Maintainers <recipes@mkdeb.sh>

source:
  url: https://dl.google.com/go/go{{ .Version }}.linux-{{ .Arch }}.tar.gz
  arch-mapping:
    amd64: amd64
    arm64: arm64
    armel: armv6l
    i386: "386"

control:
  depends:
  - libc6
  description: |
    Go is an open source programming language that makes it easy to build
    simple, reliable, and efficient software.
  section: devel
  version:
    epoch: 2

install:
  upstream:
    /usr/local:
    - pattern: go/*

links:
  /usr/bin/go: /usr/local/go/bin/go
  /usr/bin/godoc: /usr/local/go/bin/godoc
  /usr/bin/gofmt: /usr/local/go/bin/gofmt

# vim: ts=2 sw=2 et
