#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          prometheus-stackdriver-exporter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prometheus exporter for stackdriver
# Description:       Prometheus exporter for stackdriver
### END INIT INFO

NAME="prometheus-stackdriver-exporter"
DESC="Prometheus exporter for stackdriver"
USER="prometheus"
GROUP="prometheus"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON=/usr/bin/$NAME

LOGFILE="/var/log/prometheus/stackdriver-exporter.log"
PIDFILE="/var/run/prometheus/stackdriver-exporter.pid"

HELPER="/sbin/start-stop-daemon"
HELPER_ARGS="--make-pidfile --pidfile=$PIDFILE --chuid $USER"

do_start_prepare() {
    install -m 0755 -o $USER -g $GROUP -d $(dirname $PIDFILE)
}

do_start_cmd() {
    $HELPER --start --background $HELPER_ARGS --exec /bin/bash -- -c "exec $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1"
}

do_stop_cmd() {
    $HELPER --stop --pidfile=$PIDFILE
}

# vim: ft=sh ts=4 sw=4 et