#!/bin/sh
# postinst script for vault

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see https://www.debian.org/doc/debian-policy/ or
# the debian-policy package

set_perms() {
    if ! dpkg-statoverride --list "$4" >/dev/null; then
        dpkg-statoverride --update --add "$@"
    fi
}

case "$1" in
    configure)
        if ! getent passwd vault >/dev/null; then
            adduser --quiet --system --group --home /var/lib/vault --no-create-home vault
        fi

        set_perms vault vault 0755 /var/lib/vault
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -x /usr/bin/deb-systemd-helper ]; then
    if deb-systemd-helper --quiet was-enabled vault.service; then
        deb-systemd-helper enable vault.service >/dev/null || true
    else
        deb-systemd-helper update-state vault.service >/dev/null || true
    fi
fi

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ]; then
    update-rc.d vault defaults >/dev/null
    invoke-rc.d vault start || exit $?
fi

exit 0
