#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          consul
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: service discovery and configuration tool
# Description:       service discovery and configuration tool
### END INIT INFO

NAME="consul"
DESC="service discovery and configuration tool"

DAEMON=/usr/bin/$NAME
DAEMON_ARGS="agent -config-dir=/etc/consul.d -config-dir=/etc/consul.d/services -data-dir=/var/lib/consul"

PIDFILE=/var/run/consul.pid

START_ARGS="--chuid consul:consul --background --pidfile $PIDFILE --make-pidfile"

do_reload() {
    $DAEMON reload
}
