#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          vault
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: secrets management tool
# Description:       secrets management tool
### END INIT INFO

NAME="vault"
DESC="secrets management tool"

DAEMON=/usr/bin/$NAME
DAEMON_ARGS="server -config=/etc/vault/vault.hcl -log-level=info"

PIDFILE=/var/run/vault.pid

START_ARGS="--chuid vault:vault --background --pidfile $PIDFILE --make-pidfile"

do_reload() {
    $DAEMON reload
}
