#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          prometheus-cassandra-exporter
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Prometheus exporter for Apache Cassandra metrics
# Description:       Prometheus exporter for Apache Cassandra metrics
### END INIT INFO

NAME="prometheus-cassandra-exporter"
DESC="Prometheus exporter for Apache Cassandra metrics"
USER="prometheus"
GROUP="prometheus"

[ -r /etc/default/$NAME ] && . /etc/default/$NAME

DAEMON=/usr/bin/java

LOGFILE="/var/log/prometheus/cassandra-exporter.log"
PIDFILE="/var/run/prometheus/cassandra-exporter.pid"

HELPER="/usr/bin/daemon"
HELPER_ARGS="--name=$NAME --output=$LOGFILE --pidfile=$PIDFILE --user=$USER:$GROUP"

do_start_prepare() {
    install -d 0755 -o $USER -g $GROUP $(dirname $PIDFILE)
}

do_start_cmd() {
    $HELPER $HELPER_ARGS --running && return 1
    $HELPER $HELPER_ARGS -- $DAEMON $DAEMON_ARGS || return 2
}

do_stop_cmd() {
    $HELPER $HELPER_ARGS --running || return 1
    $HELPER $HELPER_ARGS --stop || return 2
    sleep 2s
    $HELPER $HELPER_ARGS --running && return 2
}

# vim: ft=sh ts=4 sw=4 et
